### ISSUE TITLE
Two Factor Authentication?

### ISSUE THREAD

**Issue by LoganGanieanyReddit** [jetstreamapp/jetstream#1003]
Will this be coming? It does make me a bit nervous that just email and pw can be used to access prod data

**Comment by paustint** [comment]
@LoganGanieanyReddit - yes, this will be coming.

For better security right now, you should use Google or SFDC social login options

**Comment by paustint** [comment]
@LoganGanieanyReddit - We have just completed authentication upgrade which includes MFA via email or authenticator app.


https://docs.getjetstream.app/user-profile-and-settings/user-profile

**Comment by LoganGanieanyReddit** [comment]
Nice. Much needed upgrade

*Logan Ganieany | LinkedIn
<https://www.linkedin.com/in/logan-ganieany-4a82a0b4/>*
Lead Salesforce Product Manager
*c*: (406)-531-9761 (MST)
*e: ***@***.*** ***@***.***>*
