### ISSUE TITLE
add a new org with username + password only instead of from OAuth? 

### ISSUE THREAD

**Issue by bklapholzbpa** [jetstreamapp/jetstream#1004]
Any chance of being able to add a new org with username + password only instead of from OAuth? 
There are a few use cases I currently have where this is the only option available and prevents me from using JetStream (have to use Copado/Gearset, or SFDX) to deploy changes.

**Comment by paustint** [comment]
@bklapholzbpa - Unfortunately OAuth is the only available login option to connect a Salesforce org.

What are the circumstances where you have to use insecure authentication methods (username+password)? Normally you can always overcome any issues to enable OAuth.
Here are some tips: https://docs.getjetstream.app/

And happy to help troubleshoot if you need additional assistance.

**Comment by bklapholzbpa** [comment]
- The reason for the request is to get around orgs that have SSO enabled where I am not part of the SSO and need to bypass the login url by adding "/?login=true" to end of the url.  `http://somedomain.my.salesforce.com/?login=true`

**Comment by paustint** [comment]
@bklapholzbpa - Just added an option to add login=true, can you check this out and see if it works for you?

<img width="338" alt="image" src="https://github.com/user-attachments/assets/e2dd06fa-30cc-405d-9cfd-676c29b294ea">

**Comment by bklapholzbpa** [comment]
Thanks!  It worked perfectly.
