### ISSUE TITLE
Links to Sandbox Environments - You must be logged in

### ISSUE THREAD

**Issue by anthonygiuliano** [jetstreamapp/jetstream#1090]
**Describe the bug and steps to reproduce**
In Sandbox environments, links including Home Page, Setup, and links to record detail pages have started landing on a login page saying "To access this page, you have to log in to Salesforce." Further, logging in from here lands you right back to the same login page. I think it has something to do with the "return URL".

Links to my production environment still work as expected, but all the sandboxes I've tried have this behavior now.

Use any of these links from a sandbox environment:

![CleanShot 2024-11-22 at 08 44 05@2x](https://github.com/user-attachments/assets/8bc0e462-eab1-4ff3-8f3d-263cbc68cf64)
![CleanShot 2024-11-22 at 08 51 44@2x](https://github.com/user-attachments/assets/f1e6fae0-1e72-4aed-83b3-9506307bb054)

You'll land here and be unable to log in.

![CleanShot 2024-11-22 at 09 20 04@2x](https://github.com/user-attachments/assets/f3b60e93-b76f-43f9-8f7e-c12313051b14)

**Expected behavior**

Should authenticate and land at the appropriate page in Salesforce

**Browser and operating system:**

Chrome Version 131.0.6778.86 (Official Build) (arm64)
MacOS 15.1.1 (24B91)

**Comment by paustint** [comment]
Thank you for the report! Other people had reported the issue but i couldn't reproduce as I didn't try with a sandbox - we will take a look again.

**Comment by paustint** [comment]
Turns out that this was a regression caused by the removal of the `web` oauth2 scope. Any orgs authenticated after the scope was removed don't work with frontdoor login.

This means that all users will need to re-authenticate any recently connected orgs for the frontdoor login process to work.

**Comment by paustint** [comment]
@anthonygiuliano - The fix is being deployed and should take 10-15 minutes. After that you will need to re-authorize your org and everything should work as it was.

Sorry for the regression!
