### ISSUE TITLE
Can't validate reCaptcha if first password entered is incorrect

### ISSUE THREAD

**Issue by LoganGanieanyReddit** [jetstreamapp/jetstream#1101]
Steps to reproduce:

1. Go to the new login screen
2. Enter your email and an incorrect password
3. Try and login and get an error
4. Change password to the correct password
5. Notice that you still can't login due to a recaptcha issue

**Comment by paustint** [comment]
@LoganGanieanyReddit - Thank you for filing - this was on my list of "annoying things to fix", but I forgot about it.

**Comment by paustint** [comment]
Actually I had this option as resolved... but it looks like it is not resolved: https://github.com/jetstreamapp/jetstream/issues/1076
