### ISSUE TITLE
Add option to include child relationship name in sobject export

### ISSUE THREAD

**Issue by paustint** [jetstreamapp/jetstream#1102]
**Describe the problem you are trying to solve**
https://discord.com/channels/246568944213819393/955492316116844595/1314689049469915157

This would be a nice data point to have in the report - but it does not fetching a bunch of related data. Maybe there is a SOQL query that we can use to fetch the data without having to do a ton of `describeSobject` calls.

**Comment by infocynic** [comment]
I'm also ok with flipping this - an option to export child relationship data when exporting a parent. That might be far less painful since you already run the describe for the parent object and can just get the child relationships along with the restricted delete / cascade delete options.
