### ISSUE TITLE
Restore button within SOQL query builder doesn't restore the Query

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#154]
**Query**
SELECT ID FROM Opportunity WHERE AccountId = '0013t00001nJsHJAA0'     AND (         poreliteSTATc = 'Open'         OR poreliteSTATc = 'Called Off Rent'     )     AND ( (NOT Name LIKE 'H%')     OR (NOT Name LIKE 'L%')     OR (NOT Name LIKE 'W%')     OR (NOT Name LIKE 'R%')     )

**Steps to Reproduce:**
1. Query Records
2. Object = Opportunity
3. Click Manual Query ( I clicked the one below the Text Area field )
4. Paste in Query ( provided above )
5. Click "Restore"
-- The screen blips but nothing happens

**Expected Results**
The query to be parsed and the conditions restored in JetStream

**Actual Results**
The screen blips but nothing happens.

**Workaround**
Execute the query
Paste the updated query you want
Click Format
Click Back. 
All conditions and fields are now there.

**Comment by paustint** [comment]
Appears that this might happen if the query being restored uses the same object that is already selected.
E.x. if `Opportunity` is selected and the soql includes `FROM Opportunity`, then the restore does not seem to apply.
