### ISSUE TITLE
Google Drive Integration

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#175]
**Describe the bug**
When running a query and clicking Download and export to Google Drive, none of the accept or cancel buttons work.

**To Reproduce**

1. run a query
2. Click Download
3. Select Drive
4. Authorize ( optional )
5. Select a folder
6. Try to click Select or Cancel nothing happens

**Expected behavior**
To select the folder

**Environment:**

- OS: Windows
- Browser: Chrome Latest

**Comment by paustint** [comment]
@AndyHaas - I have seen this before and cannot for the life of me figure out why it is happening.

If you double click on a folder or file does it select it? That is the behavior I had seen locally.

**Comment by paustint** [comment]
@AndyHaas - Should be fixed (make sure to hard refresh), closing now - let me know if you still have issues and I can reopen.
