### ISSUE TITLE
Deployment Payload Error: No package.xml found when trying to deploy metadata using 'Deploy to Different Org' button

### ISSUE THREAD

**Issue by alxman2021** [jetstreamapp/jetstream#198]
When trying to deploy metadata from one org to another using the 'Deploy to Different Org' button (was trying to move some custom fields), I'm receiving a 'No package.xml found' error.

I can use the 'Download Metadata' button in source org, then change to target org and click the 'Upload Metadata Zip' button to upload the package as a successful workaround.

**Comment by paustint** [comment]
@alxman2021 - Sorry for the inconvenience, there was a regression that slipped through last week. A fix will be out shortly.
