### ISSUE TITLE
Add Group By And Having to Query Records Page

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#255]
I want to add Group By and Having within the Query Page.

Example query

```sql

SELECT Account.Name, COUNT(Id)
FROM Contact
WHERE AccountId != null
GROUP BY Account.Name
HAVING COUNT(Id) > 1
```

**Comment by paustint** [comment]
# Thoughts on implementation

1. Add GROUP BY section above ORDER BY
2. GROUP BY should allow multiple fields
    * Need to figure out how to allow functions in group by
4. Include HAVING expression builder in same place that is available
    * Need to figure out how to allow functions on the selection
    * Maybe there is a simple watered down implementation for these for initial build - could exclude grouping (parens) etc..
5. Add ability to add functions to fields in query
    * Not 100% sure where to add this - probably in the right part of page somewhere, but could also be added near where the field is selected. The main issue is that some functions are aggregate-only functions and others can be applied to normal queries (some specific based on type of field)

Need to add to query builder and query restore

## Field-level functions
These can be added to fields (there are also location functions and FIELDS functions, but probably won't worry about them now)

### OTHER FUNCTIONS
* Format
* Tolabel
* ConvertTimeZone
* ConvertCurrency
* Grouping

### AGGREGATE FUNCTIONS
* Avg
* Count
* CountDistinct
* Min
* Max
* Sum

### DATE FUNCTIONS
* CalendarMonth
* CalendarQuarter
* CalendarYear
* DayInMonth
* DayInWeek
* DayInYear
* DayOnly
* FiscalMonth
* FiscalQuarter
* FiscalYear
* HourInDay
* WeekInMonth
* WeekInYear

## Group By Clause Functions
May not support these initially, need to work through details
* Cube
* Rollup
* (and all date functions can be used)

### Example Group By Query 
Taken from test-case example file here https://github.com/jetstreamapp/soql-parser-js/blob/master/docs/static/sample-queries-json.json
* `SELECT LeadSource, COUNT(Name) FROM Lead GROUP BY LeadSource"`
* `SELECT Name, COUNT(Id) FROM Account GROUP BY Name HAVING COUNT(Id) > 1"`
* `SELECT UserId, COUNT(Id) FROM LoginHistory WHERE LoginTime > 2010-09-20T22:16:30.000Z AND LoginTime < 2010-09-21 GROUP BY UserId"`
* `SELECT CampaignId, AVG(Amount) avg FROM Opportunity GROUP BY CampaignId HAVING COUNT(Id, Name) > 1"`
* `SELECT LeadSource, COUNT(Name) cnt FROM Lead GROUP BY ROLLUP(LeadSource)"`
* `SELECT Status, LeadSource, COUNT(Name) cnt FROM Lead GROUP BY ROLLUP(Status, LeadSource)"`
* `SELECT Type, BillingCountry, GROUPING(Type)grpType, GROUPING(BillingCountry) grpCty, COUNT(id) accts FROM Account GROUP BY CUBE(Type,BillingCountry) ORDER BY GROUPING(Type), GROUPING(Id,BillingCountry), Name DESC NULLS FIRST, Id ASC NULLS LAST"`
* `SELECT LeadSource, COUNT(Name) FROM Lead GROUP BY LeadSource HAVING COUNT(Name) > 100 AND LeadSource > 'Phone'"`
* `SELECT CALENDAR_YEAR(CreatedDate) calYear, SUM(Amount) mySum FROM Opportunity GROUP BY CALENDAR_YEAR(CreatedDate)"`
* `SELECT CALENDAR_YEAR(convertTimezone(CreatedDate)) calYear, SUM(Amount) mySum FROM Opportunity GROUP BY CALENDAR_YEAR(convertTimezone(CreatedDate))"`
* `SELECT LeadSource, Rating, GROUPING(LeadSource) grpLS, GROUPING(Rating) grpRating, COUNT(Name) cnt FROM Lead GROUP BY ROLLUP(LeadSource, Rating)"`
* `SELECT Type, BillingCountry, GROUPING(Type) grpType, GROUPING(BillingCountry) grpCty, COUNT(id) accts FROM Account GROUP BY CUBE(Type, BillingCountry) ORDER BY GROUPING(Type), GROUPING(BillingCountry)"`
* `SELECT HOUR_IN_DAY(convertTimezone(CreatedDate)), SUM(Amount) FROM Opportunity GROUP BY HOUR_IN_DAY(convertTimezone(CreatedDate))"`
* `SELECT Name, COUNT(Id) FROM Account GROUP BY Name HAVING COUNT(Id) > 0 AND (Name LIKE '%testing%' OR Name LIKE '%123%')"`
* `SELECT Name, COUNT(Id) FROM Account GROUP BY Name HAVING COUNT(Id) > 0 AND (Name IN ('4/30 testing account', 'amendment quote doc testing', null))"`
* `SELECT Name, COUNT(Id) FROM Account GROUP BY Name HAVING COUNT(Id) > 0 AND (NOT Name IN ('4/30 testing account', 'amendment quote doc testing'))"`
* `SELECT BillingState, BillingStreet, COUNT(Id) FROM Account GROUP BY BillingState, BillingStreet"`
* `SELECT SBQQ__Product__r.Name foo, SBQQ__Quote__c foo1 FROM SBQQ__Quoteline__c GROUP BY SBQQ__Quote__c, SBQQ__Product__r.Name"`
* `SELECT ProductCode FROM Product2 GROUP BY ProductCode HAVING COUNT(Id) > 1 ORDER BY COUNT(Id) DESC"`
* `SELECT WEEK_IN_YEAR(CloseDate), SUM(amount) FROM Opportunity GROUP BY WEEK_IN_YEAR(CloseDate) ORDER BY WEEK_IN_YEAR(CloseDate)"`
* `SELECT WEEK_IN_YEAR(CloseDate), SUM(amount) FROM Opportunity GROUP BY WEEK_IN_YEAR(CloseDate) ORDER BY WEEK_IN_YEAR(CloseDate) DESC NULLS FIRST"`
* `SELECT WEEK_IN_YEAR(CloseDate), SUM(amount) FROM Opportunity GROUP BY WEEK_IN_YEAR(CloseDate) ORDER BY WEEK_IN_YEAR(CloseDate) DESC NULLS LAST, SUM(amount) ASC NULLS LAST"`
* `SELECT UserId, CALENDAR_MONTH(LoginTime) month FROM LoginHistory WHERE NetworkId != NULL GROUP BY UserId, CALENDAR_MONTH(LoginTime)"`
* `SELECT LeadSource, COUNT(Name) FROM Lead GROUP BY LeadSource HAVING COUNT(Name) > 100 AND LeadSource > 'km'"`
