### ISSUE TITLE
Same Object Lookup Doesn't Support By Field

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#257]
**Issue:**
When you select the Id field within Load Records on an object, you are not given the option to use a field to look up that record.

**Steps to Reproduce**
1. From Load Records
2. Click on Load Records
3. Select Contact ( Any object would do )
4. Select a file
5. Select Update
6. Continue to Load Records 
7. Within the Mapping Fields, change one of the fields to Contact Id ( In the example we are using, we changed the email to Contact Id )
8. No additional fields are provided as this lookup is on the same object. 

If you chose Account Id, you could select a field to search by.

![image](https://user-images.githubusercontent.com/22582720/228934606-7e3efd4d-6af1-4e8c-855c-aecb2fb7bd73.png)

**Expected Results**
When choosing the Id field of any object, we should be allowed to look up based on another field.

**Comment by paustint** [comment]
This is a special case since it is not a relationship field - if mapped to a related field, it cannot make use of an external id and must query the records to find how to perform the mapping.

Need to spend some time digging in and figure out how to approach.

**Comment by matthewctrl** [comment]
@paustint Makes sense. Tools like Dataloader.io have the ability to do this but I have found that a lot of other data import tools do not have this functionality. Example of this below: 
<img width="1223" alt="Screenshot 2023-04-03 at 12 15 36 PM" src="https://user-images.githubusercontent.com/129790258/229605584-7222d675-ec9e-491d-8ad9-d5a2318737bf.png">

**Comment by paustint** [comment]
Sorry I should have clarified, the comments were more of a note to myself. 😁

This is a good feature and it will be added, it is just a bit more work to handle so was calling that out as a reminder once the ticket starts being worked on. 

Thanks for the screenshot and extra context.
