### ISSUE TITLE
LOAD RECORDS | Add Stop Function for Load Records

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#301]
When uploading records and you have it set to Batch API or Bulk API, it would be nice to have an abort button. Just in case you have an Oh Sh*t moment or notice everything is erroring out. 

![Screenshot 2023-04-13 at 8 46 55 PM](https://user-images.githubusercontent.com/22582720/231920366-f30b5fea-3a71-4f41-88b2-26a13db9a95d.png)

**Comment by paustint** [comment]
I had worked through this at one point and can re-visit.
The Bulk API cancellation will only cancel unprocessed batches - so if there is just one batch the cancellation does not do anything.
For batch we can cancel.

I think it is worth adding - probably with some messaging "attempting to cancel" type of thing.

**Comment by AndyHaas** [comment]
For the Bulk API I think that is fine, still sucks if you upload crap data but that is on the end user. ( Aka me ) 

Bringing the cancel/rollback feature for batch would be great to have. 

And your messaging has to actually update tho :) I recall recently it was stuck in "Attempting to Cancel" and never updated haha.
