### ISSUE TITLE
LOAD RECORDS | Within the Load Results Screen add tooltip or allow expanding the rows to see entire error

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#302]
When an error happens, and the error text is too long, the text is cut off, and you can't expand/scroll to see the entire text. Luckily I get the error emails, so I do have the details. But if someone didn't have that turned on, they would rely on this to see the entire error. 

![Screenshot 2023-04-13 at 8 49 06 PM](https://user-images.githubusercontent.com/22582720/231920665-8d9de068-5243-4d65-a7b7-b459acf1d768.png)

**Comment by paustint** [comment]
@joiecosby - this might be a good ticket for you to look into.
