### ISSUE TITLE
Typo mistake on email registration confirmation

### ISSUE THREAD

**Issue by JTH-Modis** [jetstreamapp/jetstream#316]
**Describe the bug and steps to reproduce**
Create a Jetstream account
An email notification with object "Welcome to **Jestream**"
**Expected behavior**
An email notification with object "Welcome to Jetstream"

![image](https://user-images.githubusercontent.com/88449123/232441584-61bd3cb9-a09e-421e-b3f7-9f8e6635c861.png)
**Browser and operating system:**

**Comment by paustint** [comment]
@JTH-Modis - THANK YOU - 🤦 dumb mistake that went missed for a long time.
This is now resolved (updated Auth0 configuration)
