### ISSUE TITLE
BUG: Query Record: Copy to Clipboard : Text Doesn't work

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#383]
**Describe the bug and steps to reproduce**
1. Run a query
Select Id From Account Limit 5
2. Click on the "copy to clipboard button" and attempt to paste in a notepad nothing will happen
3. click the drop down and click text and attempt to paste in a notepad nothing will happen
4. Click on drop down and click JSON and attempt to paste in a notepad and json will be outputted in the notepad

**Expected behavior**
Wehn you click the Button "Copy to Clipboard" it should default to text and should copy the records into the users clipboard. 

Same goes when you click the drop down next to "Copy to Clipboard" and choose text it should copy the queried data into the users clipboard

**Browser and operating system:**
Chrome:MacOs

**Comment by paustint** [comment]
resolved by https://github.com/jetstreamapp/jetstream/pull/385
