### ISSUE TITLE
Update Records - View Results Not Showing Boolean Values Correctly

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#412]
When you are doing an update/insert of records and you have one field that is a boolean the "View Results" button won't show the the value that was set. 

This is after an update/insert has happened and you click "VIew Results"

Here is from the JS tool 
![Screenshot 2023-06-23 at 09 25 45](https://github.com/jetstreamapp/jetstream/assets/22582720/a496c6b5-82fc-4638-8d10-f327b1e53178)

here is the actual data in SF
![Screenshot 2023-06-23 at 09 25 53](https://github.com/jetstreamapp/jetstream/assets/22582720/58f5f8ec-2bb9-4d12-8aca-59d21fc500e8)

**Comment by paustint** [comment]
![image](https://github.com/jetstreamapp/jetstream/assets/5461649/692603eb-b760-4aaf-bb1f-4dc07b58af38)
