### ISSUE TITLE
LOAD RECORDS | Show what type of load we are doing

### ISSUE THREAD

**Issue by AndyHaas** [jetstreamapp/jetstream#435]
While in the Load Records section, you have the option to select Insert, Update, Upsert, or Delete. It would be beneficial to have a record of your selection on the following page. This is particularly useful when performing multiple uploads simultaneously, as you may forget which type of data load you've chosen and have to click back to Previous Steps, which could result in losing your mappings.

![Screenshot 2023-07-03 at 18 42 15](https://github.com/jetstreamapp/jetstream/assets/22582720/2437d3bd-21c9-4540-bbb3-1d15bcf5875d)
![Screenshot 2023-07-03 at 18 42 05](https://github.com/jetstreamapp/jetstream/assets/22582720/855377d4-303b-4c41-9cf9-d712ffdd093b)

**Comment by paustint** [comment]
@AndyHaas The type of load is displayed in the sub-header.

Maybe it is too discreet?

<img width="736" alt="image" src="https://github.com/jetstreamapp/jetstream/assets/5461649/1b78a93d-6e03-4b0c-a054-fa2cf955f868">

**Comment by AndyHaas** [comment]
Nah, that works. Didn't see it there. Was seeing "Load Records" didn't event think to look at the sub label.
