### ISSUE TITLE
Query results editor - improvements

### ISSUE THREAD

**Issue by paustint** [jetstreamapp/jetstream#446]
**Describe the problem you are trying to solve**
After save, re-query all modified records to get their updated state (if any).
e.x. automation or default values could have caused changes (e.x. setting record type to null sets to master record type).

We should use the same query, but replace where clause with id's that were modified to get their potentially updated values in the table.

**Comment by paustint** [comment]
current behavior is good enough

**Comment by AndyHaas** [comment]
I agree, the only thing I would add is the re-query can be a bit painful if you set up filters on the query.

**Comment by paustint** [comment]
@AndyHaas - I think that after an update and the modal closes, the query is re-executed so all the records should show the latest information.

Am I missing a use-case where this doesn't happen? I closed it because I thought that was good enough - but if there is still some annoying thing, LMK.
