### ISSUE TITLE
JSON_PARSER_ERROR:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name at [line:2, column:34667]

### ISSUE THREAD

**Issue by rochellecurrier** [jetstreamapp/jetstream#538]
I am using the Load Records to Multiple Records feature. I was able to use this feature successfully several times, but I'm working with new data and now I'm getting the error below for several hundred rows. I'm not sure how to troubleshoot this. My data and headers all look valid to me (the headers are the same as when I was working with a different data set).

`JSON_PARSER_ERROR:   Unexpected character ('}' (code 125)): was expecting double-quote to start   field name at [line:2, column:34667]`

**Comment by paustint** [comment]
@rochellecurrier sorry about the issue, this one might be difficult to troubleshoot without access to the file.

What spreadsheet software did you use to create the file?

Any way you could provide a minimal file that reproduces the error?

Is there anything else you can think of that might be different in this file? Is there possibly data stored in cells outside of where you have headers?

**Comment by rochellecurrier** [comment]
@paustint I'm using Google Sheets. I think I pasted in something odd from another spreadsheet because when I started fresh and made sure to only paste in the rows with data, the Insert worked.
