### ISSUE TITLE
Authentication Error related to orgLanguageLocaleKey

### ISSUE THREAD

**Issue by nathanvoller** [jetstreamapp/jetstream#573]
**Describe the bug and steps to reproduce**

Trying to login to a developer edition org. Authentication fails with this error message:

```
Invalid+`prisma.salesforceOrg.create()`+invocation: { ..., orgLanguageLocaleKey:+"en_GB", ... }
Invalid+value+for+argument+`orgLanguageLocaleKey`.+Expected+salesforce_org_orglanguagelocalekey_enum.

There+was+an+error+authenticating+with+Salesforce.
```

In Company Information, the following were currently set:

- Default Locale: **English (United Kingdom)**
- Default Language: **English (UK) (End-User)**

but if I change them to:
- Default Locale: **English (United States)**
- Default Language: **English**

it works as expected. Looking at the error message I assume the issue is with the Default Language option.

**Expected behavior**

Ability to login with any language locale.

**Browser and operating system:**

- Google Chrome Version 116.0.5845.140 (Official Build) (x86_64)
- macOS Ventura 13.4.1

**Comment by paustint** [comment]
@nathanvoller - Sorry for the inconvenience, I will take a look at this soon.
