### ISSUE TITLE
Error trying to update CMTD

### ISSUE THREAD

**Issue by Omar-G-Reddit** [jetstreamapp/jetstream#587]
When trying to update a CMTD object I get the error "there was a problem preparing the custom metadata for deployment. Please check your file and try again. I have tried CSV,XLS, and XLSX but all have given me the same error. 

![image](https://github.com/jetstreamapp/jetstream/assets/108813252/f0f48cd5-c1d4-4957-8d6b-818bbd3eff16)

**Comment by paustint** [comment]
@Omar-G-Reddit - Any chance you would be able to share your custom metadata definition (download from metadata page) and the file you are using?

You can email to support@getjetstream.app and I can help troubleshoot.

Thanks!

**Comment by paustint** [comment]
@Omar-G-Reddit - Disregard, I figured out what the issue was. If you did not map every writeable field for custom metadata, then there was a problem preparing the file. Working on getting a fix out shortly.
