### ISSUE TITLE
Loading Records Seems To Miss the First Record

### ISSUE THREAD

**Issue by josephdesch** [jetstreamapp/jetstream#655]
**Describe the bug and steps to reproduce**
When loading records, the insert/update/etc seems to be ignoring/missing the first record of the sheet. Even when loading in only one record, it recognizes the record in the sheet until it's time to insert. (see screenshot).

**Expected behavior**
Load operation of Jetstream recognizes all records in upload sheets.

**Browser and operating system:**
Chrome, Windows 10

![Jetstream Potential Bug Screenshot - Desch - 12-4-23](https://github.com/jetstreamapp/jetstream/assets/29467690/7fa4065a-16e3-4d62-88a0-2a374308b718)

![image](https://github.com/jetstreamapp/jetstream/assets/29467690/7da79bed-1bc9-41f2-bb88-288fc0c01899)

**Comment by paustint** [comment]
@josephdesch - Whoops, this is related to the new trial run feature. Deploying release now, immediate term workaround is to check and uncheck the trial run checkbox.

**Comment by josephdesch** [comment]
Thank you! Appreciate the quick fix.
