### ISSUE TITLE
Add Tab Settings to Object Permissions in Manage Permissions

### ISSUE THREAD

**Issue by jhaisley** [jetstreamapp/jetstream#663]
**Frequently when adjusting permissions, it's necessary to adjust the tab settings as well.**

**Add tab settings to Manage Permissions **

![image](https://github.com/jetstreamapp/jetstream/assets/413583/b6285316-501c-4a28-95ea-96e968a2cb2c)

**Comment by paustint** [comment]
@jhaisley - Thank you for raising this ticket. The ability to adjust Tab Visibility will be coming shortly! 🎉
