### ISSUE TITLE
See related records from a record Id

### ISSUE THREAD

**Issue by TijsDeBelie** [jetstreamapp/jetstream#70]
**Describe the problem you are trying to solve**
When looking for related records we want to see a list of these records we can also mass update

**Describe the solution you'd like**
Clicking the search record with ID button in the right upper corner we can search for the record, and it the resulting view should have a tab to see related records. These related records should have an edit property so you can update them, or even mass update them.

**Comment by paustint** [comment]
Thank you for the suggestion! - I think traversing across records is a great feature.

Mass loads these records is also a good idea, but will take some thought on the experience would look like.
