### ISSUE TITLE
Query Returns Blank

### ISSUE THREAD

**Issue by Brandon-J88** [jetstreamapp/jetstream#702]
Here is my query. When I run this, it returns the number of records, but not the actual data. If I remove the very bottom and statement, it works fine. The bottom item is a formula field. If I try other formula fields in it's place, it totally works. Kinda strange.

SELECT Id, blng__Balance__c, Return_Item_Count__c
FROM blng__Invoice__c
WHERE blng__InvoiceRunCreatedBy__r.Name LIKE '%Usage%'
	AND CreatedDate = THIS_MONTH
	AND blng__InvoiceStatus__c = 'Draft'
	AND (NOT Invoice_Type__c LIKE '%Usage%')

![Screenshot 2024-01-11 150706](https://github.com/jetstreamapp/jetstream/assets/156374962/02612f94-bb54-4a91-85e7-1c5fbd564b7f)

**Comment by paustint** [comment]
@Brandon-J88 - really weird. Can you:

1. Go to your settings and turn on logging
2. Open up your browser dev-tools (right click anywhere on the page and choose inspect, then click the "console" tab)
3. Run your query - See what shows up in the console

Are there errors shown there (and if so, what error).

**Comment by Brandon-J88** [comment]
This is what I got in the console.

WARN Could not parse query from location state SELECT Id, blng__Balance__c,
Return_Item_Count__c
FROM blng__Invoice__c
WHERE blng__InvoiceRunCreatedBy__r.Name LIKE '%Usage%'
AND CreatedDate = THIS_MONTH
AND blng__InvoiceStatus__c = 'Draft'
AND (NOT Invoice_Type__c LIKE '%Usage%') Expecting: one of these possible
Token sequences:
  1. [AVG, L_PAREN]
  2. [COUNT, L_PAREN]
  3. [COUNT_DISTINCT, L_PAREN]
  4. [MIN, L_PAREN]
  5. [MAX, L_PAREN]
  6. [SUM, L_PAREN]
  7. [DISTANCE, L_PAREN]
  8. [CALENDAR_MONTH, L_PAREN]
  9. [CALENDAR_QUARTER, L_PAREN]
  10. [CALENDAR_YEAR, L_PAREN]
  11. [DAY_IN_MONTH, L_PAREN]
  12. [DAY_IN_WEEK, L_PAREN]
  13. [DAY_IN_YEAR, L_PAREN]
  14. [DAY_ONLY, L_PAREN]
  15. [FISCAL_MONTH, L_PAREN]
  16. [FISCAL_QUARTER, L_PAREN]
  17. [FISCAL_YEAR, L_PAREN]
  18. [HOUR_IN_DAY, L_PAREN]
  19. [WEEK_IN_MONTH, L_PAREN]
  20. [WEEK_IN_YEAR, L_PAREN]
  21. [FORMAT, L_PAREN]
  22. [toLabel, L_PAREN]
  23. [convertTimezone, L_PAREN]
  24. [convertCurrency, L_PAREN]
  25. [GROUPING, L_PAREN]
  26. [Identifier]
but found: 'NOT In'

**Comment by paustint** [comment]
@Brandon-J88 - Turns out there is a query parsing error because `(NOT Invoice_Type__c LIKE '%Usage%')` is incorrectly being parsed as `NOT In` - the first two characters of the field name are tripping the parser up, which is why other fields worked fine here.

Thanks for reporting and I am taking a look.

**Comment by paustint** [comment]
@Brandon-J88 - A new version of Jetstream is being deployed with a fix, should be live in ~10 minutes. You may need to do a hard refresh (cmd/ctrl+shift+r) to make sure you don't get a cached version of Jetstream.

**Comment by Brandon-J88** [comment]
Thanks Austin! Worked like a charm!
