### ISSUE TITLE
Mass upload records from clipboard

### ISSUE THREAD

**Issue by TijsDeBelie** [jetstreamapp/jetstream#71]
**Describe the problem you are trying to solve**
Uploading records now requires a file, but often you just want to copy paste the data from excel. 

**Describe the solution you'd like**
A way to paste excel/CSV data in the load records tab. Show a preview of the data and adjust the mapping of the pasted data to the correct salesforce columns.

**Comment by paustint** [comment]
@TijsDeBelie - This is a great idea and would probably be pretty easy to implement in the existing data loader, just a different source of data.
