### ISSUE TITLE
Removing Value of a Number Field in in-line Query Editor Inserts a 0

### ISSUE THREAD

**Issue by josephdesch** [jetstreamapp/jetstream#747]
**Describe the bug and steps to reproduce**
Using the in-line editor in the query feature inserts a 0 instead of a null into number fields when clearing the value.

**Expected behavior**
The value is set to null upon clear.

**Browser and operating system:**
Google Chrome, Windows 10

Screenshots of Behavior attached
![Jetstream In-Line Edit Bug Screenshot 1](https://github.com/jetstreamapp/jetstream/assets/29467690/198f0e72-2858-4015-a0a0-c1cf4a1d02ca)
![Jetstream In-Line Edit Bug Screenshot 2](https://github.com/jetstreamapp/jetstream/assets/29467690/04e5d74d-a53a-4dc0-8847-66831b571ca8)

**Comment by paustint** [comment]
@josephdesch - Thanks for the bug report and really appreciate the screenshots!

Have a [fix in place](https://github.com/jetstreamapp/jetstream/pull/748) and will work on getting deployed to production soon, you can monitor the releases to see when the release deployment to production is kicked off.
You can also subscribe to releases via Github's notifications if you want to get emails of any release

Cheers Joe!
