### ISSUE TITLE
{"error":"There was an error processing the request","message":"Bad_OAuth_Token"}

### ISSUE THREAD

**Issue by adwork1512** [jetstreamapp/jetstream#793]
![image](https://github.com/jetstreamapp/jetstream/assets/115721112/aa8af117-c0ce-417c-b7c9-87bf00057d3a)

while logging into org this happens

**Comment by paustint** [comment]
@adwork1512 - A fix for this is in the works and should be deployed in the next 10-15 minutes  - sorry for the inconvenience!

**Comment by paustint** [comment]
Resolved - related to token refresh bug
