### ISSUE TITLE
Unselect all visible rows unselects everything

### ISSUE THREAD

**Issue by LFCnmart24** [jetstreamapp/jetstream#845]
Then unselect all visible rows unselects everything, whether or not if it is filtered

**Describe the bug and steps to reproduce**
When I go to manage profiles and are selecting Field permission, the unselect all visible rows actually unselects everything whether or not it is filtered

**Comment by paustint** [comment]
@LFCnmart24 - can you provide more information, I am not able to reproduce the issue so there may be something I am not doing the same as you are.

Here is a video of what I have tried: https://jam.dev/c/01809f4d-20be-43c2-aeec-be78c4dbbe14

**Comment by LFCnmart24** [comment]
Last email didn't go through because of the video, so here is a link to it https://drive.google.com/file/d/1X__0UqF5oA1MDXcDhBaZYinzUpASWT4F/view?usp=sharing
________________________________

**Comment by paustint** [comment]
@LFCnmart24 - Appreciate the detailed walkthrough - I will take a look and figure it out.
