### ISSUE TITLE
Automation Control - Add Duplicate Rules

### ISSUE THREAD

**Issue by soileaud** [jetstreamapp/jetstream#880]
I've been using automation control to turn off vast amounts of automation prior to data seeding, but I still have to manually turn off a few duplicate rules to prevent errors in the data load. If automation control was able to also show/control duplicate rules on an object, this would be a great time saver.

**Comment by paustint** [comment]
@soileaud - Thank you for the suggestion, that makes a lot of sense!
we will take a look into it. 😄
